import type { Card } from "./types";

export const CARDS: Card[] = [
  {
    id: "mosswood-jack",
    name: "Mosswood Scout",
    rarity: "common",
    role: "Lumberjack",
    kind: "crew",
    cost: 2,
    power: 5,
    description: "Harvests timber. Double yield in the grove.",
    artIndex: 0,
    affinity: "wood",
    cooldown: 22,
    duration: 30,
  },
  {
    id: "granite-guard",
    name: "Stoneguard",
    rarity: "common",
    role: "Miner",
    kind: "crew",
    cost: 2,
    power: 4,
    description: "Mines stone. Protects you and guards its site.",
    artIndex: 1,
    affinity: "stone",
    cooldown: 24,
    duration: 32,
  },
  {
    id: "tide-witch",
    name: "Riverwitch",
    rarity: "rare",
    role: "Channeler",
    kind: "crew",
    cost: 3,
    power: 3,
    description: "Draws essence. Restores health each harvest.",
    artIndex: 3,
    affinity: "essence",
    cooldown: 28,
    duration: 30,
  },
  {
    id: "ember-fox",
    name: "Emberfox",
    rarity: "rare",
    role: "Scout",
    kind: "crew",
    cost: 2,
    power: 3,
    description: "Fast harvests at any resource site.",
    artIndex: 2,
    affinity: "any",
    cooldown: 22,
    duration: 26,
  },
  {
    id: "rune-keeper",
    name: "Rune Smith",
    rarity: "epic",
    role: "Runesmith",
    kind: "crew",
    cost: 4,
    power: 5,
    description: "Channels ancient runes. Doubles shrine points.",
    artIndex: 7,
    affinity: "essence",
    cooldown: 36,
    duration: 34,
  },
  {
    id: "elder-stag",
    name: "Moon Stag",
    rarity: "legendary",
    role: "Guardian",
    kind: "crew",
    cost: 5,
    power: 6,
    description: "Harvests everywhere. Restores 25 health.",
    artIndex: 6,
    affinity: "any",
    cooldown: 42,
    duration: 38,
  },
  {
    id: "bramble-scout",
    name: "Thorn Archer",
    rarity: "common",
    role: "Forager",
    kind: "crew",
    cost: 2,
    power: 3,
    description: "A steady gatherer. Bonus timber in the grove.",
    artIndex: 8,
    affinity: "wood",
    cooldown: 20,
    duration: 28,
  },
  {
    id: "ironbeak",
    name: "Ironbark",
    rarity: "rare",
    role: "Prospector",
    kind: "crew",
    cost: 3,
    power: 5,
    description: "Cracks rich stone. Finds bonus essence in ruins.",
    artIndex: 4,
    affinity: "stone",
    cooldown: 28,
    duration: 30,
  },
  {
    id: "sunblade",
    name: "Sun Warden",
    rarity: "epic",
    role: "Sentinel",
    kind: "crew",
    cost: 4,
    power: 6,
    description: "Claims a site. Guards it from rival captures.",
    artIndex: 10,
    affinity: "any",
    cooldown: 34,
    duration: 34,
  },
  {
    id: "wild-growth",
    name: "Frost Ward",
    rarity: "common",
    role: "Nature spell",
    kind: "spell",
    cost: 2,
    power: 16,
    description: "Restores 16 site resources and 12 health.",
    artIndex: 9,
    affinity: "any",
    cooldown: 24,
    duration: 0,
  },
  {
    id: "time-bloom",
    name: "Stormcall",
    rarity: "epic",
    role: "Time spell",
    kind: "spell",
    cost: 3,
    power: 2,
    description: "Every deployed ally harvests twice at once.",
    artIndex: 5,
    affinity: "any",
    cooldown: 32,
    duration: 0,
  },
  {
    id: "moonfall",
    name: "Dragonfall",
    rarity: "legendary",
    role: "Celestial spell",
    kind: "spell",
    cost: 5,
    power: 40,
    description: "Claims a site. Steals up to 40 rival points.",
    artIndex: 11,
    affinity: "any",
    cooldown: 44,
    duration: 0,
  },
];

export const CARD_BY_ID: Record<string, Card> = Object.assign(
  Object.create(null),
  Object.fromEntries(CARDS.map((card) => [card.id, card])),
);
export const STARTER_DECK = [
  "mosswood-jack",
  "granite-guard",
  "tide-witch",
  "ember-fox",
  "rune-keeper",
  "wild-growth",
];
export const DECK_SIZE = 6;
export const PACK_COST = 120;
export const PACK_SIZE = 3;
export const MAX_CREW = 4;
export const RARITY_ORDER = {
  common: 0,
  rare: 1,
  epic: 2,
  legendary: 3,
} as const;

export function getCard(id: string): Card | undefined {
  return CARD_BY_ID[id];
}
